### ISSUE TITLE
i dont know if this is an issue

### ISSUE THREAD

**Issue by BLINMATIC** [Fexcraft/FMT#24]
but my fmt keeps giving this
`9 Oct 2020 15:19:20(471) [main]: ==================================================
19 Oct 2020 15:19:20(474) [main]: Starting FMT! 2.6.3
19 Oct 2020 15:19:20(474) [main]: Running on Windows 10 / 10.0
[LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
19 Oct 2020 15:19:20(997) [main]: ERROR: Failed to locate library: lwjgl.dll
19 Oct 2020 15:19:20(998) [main]:       org.lwjgl.system.Library.loadSystem(Library.java:162)
19 Oct 2020 15:19:20(999) [main]:       org.lwjgl.system.Library.loadSystem(Library.java:62)
19 Oct 2020 15:19:21(000) [main]:       org.lwjgl.system.Library.<clinit>(Library.java:50)
19 Oct 2020 15:19:21(000) [main]:       org.lwjgl.stb.LibSTB.<clinit>(LibSTB.java:17)
19 Oct 2020 15:19:21(000) [main]:       org.lwjgl.stb.STBImage.<clinit>(STBImage.java:128)
19 Oct 2020 15:19:21(001) [main]:       net.fexcraft.app.fmt.utils.texture.Texture.<init>(Texture.java:30)
19 Oct 2020 15:19:21(002) [main]:       net.fexcraft.app.fmt.utils.texture.TextureManager.init(TextureManager.java:40)
19 Oct 2020 15:19:21(002) [main]:       net.fexcraft.app.fmt.FMTB.run(FMTB.java:151)
19 Oct 2020 15:19:21(003) [main]:       net.fexcraft.app.fmt.FMTB.main(FMTB.java:138)
` yes i have java 8

**Comment by Fexcraft** [comment]
Have you extracted the zip's content into a folder?
Have you tried Java 15+?
